export const RUTAS = Object.freeze({
  INICIO: 'Inicio',
  INICIO_SESION: 'InicioSesion',
  REGISTRO: 'Registro',
  PRINCIPAL: 'Principal',
  PANEL: 'Panel',
  MOVIMIENTOS: 'Movimientos',
  NUEVO: 'Nuevo',
  ESTADISTICAS: 'Estadisticas',
  SOCIAL: 'Social',
  PERFIL: 'Perfil',
  NOTIFICACIONES: 'Notificaciones',
  INGRESO: 'Ingreso',
  EGRESO: 'Egreso',
  DEPOSITO: 'Deposito',
  DETALLE_DEPOSITO: 'DetalleDeposito',
  DETALLE_CATEGORIA: 'DetalleCategoria',
  DETALLE_MOVIMIENTO: 'DetalleMovimiento',
  OCR: 'OCR',
});
