export const ROUTES = Object.freeze({
  INICIO: 'Inicio',
  LOGIN: 'Login',
  REGISTRO: 'Registro',
  PRINCIPAL: 'Principal',
  DASHBOARD: 'Dashboard',
  MOVIMIENTOS: 'Movimientos',
  NUEVO: 'Nuevo',
  ESTADISTICAS: 'Estadisticas',
  SOCIAL: 'Social',
  PERFIL: 'Perfil',
  NOTIFICACIONES: 'Notificaciones',
  INGRESO: 'Ingreso',
  EGRESO: 'Egreso',
  DEPOSITO: 'Deposito',
  DETALLE_DEPOSITO: 'DetalleDeposito',
  OCR: 'OCR',
});
