import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosDashboard(tema) {
  return StyleSheet.create({
    contenidoDesplazable: {
      paddingBottom: ESPACIADO.extraGrande,
    },
    contenidoDashboard: {
      gap: ESPACIADO.grande,
      marginTop: -ESPACIADO.pequeno,
      paddingHorizontal: ESPACIADO.medio,
      position: 'relative',
      zIndex: 1,
    },
    contenedorTarjetaBalance: {
      marginTop: -(ESPACIADO.enorme + ESPACIADO.pequeno),
      position: 'relative',
    },
    encabezadoBalance: {
      alignItems: 'center',
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
      height: ESPACIADO.enorme + ESPACIADO.pequeno,
      justifyContent: 'center',
    },
    contenidoBalance: {
      gap: ESPACIADO.grande,
      padding: ESPACIADO.grande,
    },
    textoPestanaBalance: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.medio,
    },
    tarjetaBalance: {
      backgroundColor: tema.superficie,
      borderRadius: BORDES.radios.contenedor,
      overflow: 'hidden',
      padding: 0,
    },
    filaBalance: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    filaSaldo: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
      minWidth: 0,
    },
    botonAccesoMovimientos: {
      alignItems: 'center',
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    botonVisibilidad: {
      alignItems: 'center',
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    montoBalance: {
      fontSize: 28,
    },
    lineaCargaBalance: {
      height: 30,
      width: 150,
    },
    accionesRapidas: {
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
    },
    accionRapida: {
      alignItems: 'center',
      backgroundColor: tema.botonPrincipal,
      borderRadius: BORDES.radios.boton,
      flex: 1,
      gap: ESPACIADO.minimo,
      justifyContent: 'center',
      minHeight: 78,
      paddingHorizontal: ESPACIADO.minimo,
      paddingVertical: ESPACIADO.pequeno,
    },
    accionRapidaPresionada: {
      opacity: 0.78,
      transform: [{ scale: 0.98 }],
    },
    textoAccionRapida: {
      color: tema.encabezado,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    seccion: {
      gap: 2,
    },
    encabezadoSeccion: {
      alignItems: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      minHeight: 36,
      gap: ESPACIADO.minimo,
    },
    accionSeccion: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: ESPACIADO.minimo,
    },
    textoAgregarDeposito: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    textoVerTodos: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    accionSeccionPresionada: {
      opacity: 0.62,
    },
    listaDepositos: {
      gap: ESPACIADO.minimo,
    },
    filaDeposito: {
      alignItems: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      minHeight: 64,
      paddingHorizontal: ESPACIADO.pequeno,
      paddingVertical: ESPACIADO.pequeno,
    },
    iconoDeposito: {
      alignItems: 'center',
      borderRadius: BORDES.radios.boton,
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
    detalleElemento: {
      flex: 1,
      gap: ESPACIADO.minimo,
      minWidth: 0,
    },
    nombreElemento: {
      fontWeight: TIPOGRAFIA.pesos.medio,
    },
    descripcionDeposito: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: 10,
      fontWeight: TIPOGRAFIA.pesos.regular,
    },
    saldoDeposito: {
      flexShrink: 0,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    finalDeposito: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
    },
    listaMovimientos: {
      gap: ESPACIADO.pequeno,
    },
    grupoDia: {
      gap: ESPACIADO.minimo,
    },
    tituloDia: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      paddingHorizontal: ESPACIADO.minimo,
    },
    movimientosDia: {
      gap: ESPACIADO.pequeno,
    },
    filaMovimiento: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.medio,
      minHeight: 72,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.medio,
    },
    iconoMovimiento: {
      alignItems: 'center',
      borderRadius: BORDES.radios.circular,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    filaCategoriaDescripcion: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      minWidth: 0,
    },
    categoriaMovimiento: {
      color: tema.textoPrincipal,
      flexShrink: 1,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      maxWidth: '40%',
    },
    descripcionMovimiento: {
      flex: 1,
      maxWidth: '100%',
      minWidth: 0,
    },
    separadorMetadatos: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    metaMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    tipoMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    montoMovimiento: {
      color: tema.textoPrincipal,
      flexShrink: 0,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'right',
    },
    elementoPresionado: {
      opacity: 0.82,
    },
    estadoCarga: {
      gap: ESPACIADO.grande,
      padding: ESPACIADO.grande,
    },
    lineaCarga: {
      backgroundColor: tema.fondoDeshabilitado,
      borderRadius: BORDES.radios.circular,
      height: 14,
      width: '68%',
    },
    estadoVacio: {
      alignItems: 'stretch',
      gap: ESPACIADO.medio,
      justifyContent: 'center',
      minHeight: 112,
      padding: ESPACIADO.medio,
    },
    contenidoEstadoVacio: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.medio,
      width: '100%',
    },
    iconoEstadoVacio: {
      alignItems: 'center',
      backgroundColor: tema.fondoDeshabilitado,
      borderRadius: BORDES.radios.circular,
      height: 48,
      justifyContent: 'center',
      width: 48,
    },
    textoContenidoEstadoVacio: {
      flex: 1,
      gap: ESPACIADO.minimo,
      minWidth: 0,
    },
    textoVacioTitulo: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'left',
    },
    botonCrearDeposito: {
      alignItems: 'center',
      alignSelf: 'stretch',
      backgroundColor: tema.botonPrincipal,
      borderRadius: BORDES.radios.boton,
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: ESPACIADO.medio,
    },
    textoBotonCrearDeposito: {
      color: tema.botonPrincipalTexto,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    estadoError: {
      alignItems: 'center',
      backgroundColor: tema.errorFondo,
      borderColor: tema.error,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
    },
    textoError: {
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    botonReintentar: {
      alignItems: 'center',
      backgroundColor: tema.botonPrincipal,
      borderRadius: BORDES.radios.boton,
      justifyContent: 'center',
      minHeight: 36,
      paddingHorizontal: ESPACIADO.medio,
    },
    textoReintentar: {
      color: tema.botonPrincipalTexto,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    textoEstado: {
      textAlign: 'left',
    },
  });
}
