import { StyleSheet } from 'react-native';

import { COLOR_DEPOSITO_PREDETERMINADO } from './colors';
import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosDeposito(tema) {
  return StyleSheet.create({
    contenedorTeclado: {
      flex: 1,
    },
    formulario: {
      width: '100%',
      maxWidth: 480,
      alignSelf: 'center',
      gap: ESPACIADO.formulario,
      padding: ESPACIADO.pantalla,
      paddingBottom: ESPACIADO.enorme,
    },
    grupo: {
      gap: ESPACIADO.pequeno,
    },
    filaEntrada: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    entradaTexto: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.pequeno,
    },
    botonLimpiar: {
      width: 36,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    contador: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      textAlign: 'right',
    },
    filaSaldo: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    simboloSaldo: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo + 4,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    entradaSaldo: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo + 4,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      paddingVertical: ESPACIADO.pequeno,
    },
    accionLimpiarSaldo: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    listaTipos: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    tarjetaTipo: {
      flexGrow: 1,
      flexBasis: 82,
      minWidth: 82,
      minHeight: 104,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.pequeno,
      paddingVertical: ESPACIADO.medio,
    },
    tarjetaTipoSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : tema.superficie,
    },
    tarjetaTipoError: {
      borderColor: tema.error,
    },
    iconoTipo: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
      backgroundColor: tema.fondo,
    },
    iconoTipoSeleccionado: {
      backgroundColor: tema.botonPrincipal,
    },
    nombreTipo: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    nombreTipoSeleccionado: {
      color: tema.nombre === 'oscuro' ? tema.encabezadoTexto : tema.textoPrincipal,
    },
    listaIconos: {
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      width: '100%',
    },
    botonIcono: {
      flex: 1,
      minWidth: 0,
      minHeight: 72,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.minimo,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.minimo,
      paddingVertical: ESPACIADO.pequeno,
    },
    botonMasIconos: {
      borderColor: tema.foco,
      borderStyle: 'dashed',
    },
    botonIconoSeleccionado: {
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : tema.superficie,
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    nombreIcono: {
      maxWidth: '100%',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar - 2,
      textAlign: 'center',
    },
    encabezadoColor: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    textoOpcional: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    listaColores: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
      paddingHorizontal: ESPACIADO.minimo,
      paddingVertical: ESPACIADO.minimo,
    },
    opcionColor: {
      flex: 1,
      minWidth: 0,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 64,
      gap: ESPACIADO.minimo,
    },
    muestraColor: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
    },
    muestraColorSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
      borderStyle: 'solid',
    },
    colorPredeterminado: {
      backgroundColor: COLOR_DEPOSITO_PREDETERMINADO,
    },
    nombreColor: {
      maxWidth: '100%',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar - 2,
      textAlign: 'center',
    },
    nombreColorSeleccionado: {
      color: tema.textoPrincipal,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    colorSeleccionadoInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.minimo,
    },
    indicadorColorSeleccionado: {
      width: 12,
      height: 12,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
    },
    filaDescripcion: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
      paddingTop: ESPACIADO.medio,
    },
    entradaDescripcion: {
      flex: 1,
      minHeight: 56,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      textAlignVertical: 'top',
      paddingVertical: ESPACIADO.minimo,
    },
    elementoPresionado: {
      opacity: 0.78,
    },
    fondoModal: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      padding: ESPACIADO.pantalla,
    },
    tarjetaModal: {
      width: '100%',
      maxWidth: 400,
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.medio,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    encabezadoModal: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    tituloModal: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonCerrarModal: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    opcionIconoModal: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionIconoModalSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    nombreOpcionIcono: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    mensajeError: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      backgroundColor: tema.errorFondo,
      borderColor: tema.error,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
    },
    textoMensajeError: {
      flex: 1,
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      lineHeight: 20,
    },
    acciones: {
      gap: ESPACIADO.pequeno,
      marginTop: ESPACIADO.pequeno,
    },
    botonPrincipal: {
      minHeight: 56,
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
    },
    botonPresionado: {
      opacity: 0.82,
      transform: [{ scale: 0.99 }],
    },
    textoBoton: {
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    textoProcesando: {
      color: tema.textoSecundario,
    },
    colorIndicador: tema.textoSecundario,
  });
}
