import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosDetalleDeposito(tema, anchoVentana = 390) {
  const columnasCategoriasFiltro = anchoVentana >= 420 ? 4 : 3;
  const anchoCategoriaFiltro = columnasCategoriasFiltro === 4 ? '22.5%' : '30%';

  return StyleSheet.create({
    contenido: {
      width: '100%',
      maxWidth: 560,
      alignSelf: 'center',
      gap: ESPACIADO.grande,
      padding: ESPACIADO.pantalla,
      paddingBottom: ESPACIADO.enorme,
    },
    encabezadoDeposito: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    tarjetaDeposito: {
      position: 'relative',
    },
    iconoDeposito: {
      width: 56,
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.tarjeta,
    },
    datosDeposito: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
      paddingRight: ESPACIADO.extraGrande,
    },
    botonOpciones: {
      position: 'absolute',
      top: ESPACIADO.pequeno,
      right: ESPACIADO.pequeno,
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
      backgroundColor: tema.superficie,
      zIndex: 1,
    },
    separadorSaldo: {
      height: BORDES.anchos.fino,
      marginVertical: ESPACIADO.grande,
      backgroundColor: tema.borde,
    },
    saldo: {
      marginTop: ESPACIADO.minimo,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo + 4,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    mensajeEstado: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : '#E9F2EF',
    },
    textoMensajeEstado: {
      flex: 1,
    },
    seccionMovimientos: {
      width: '100%',
      maxWidth: 480,
      alignSelf: 'center',
      gap: ESPACIADO.medio,
    },
    filaBusqueda: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    buscador: {
      flex: 1,
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      paddingLeft: ESPACIADO.medio,
      paddingRight: ESPACIADO.pequeno,
    },
    entradaBusqueda: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.minimo,
    },
    botonLimpiarBusqueda: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    botonFiltros: {
      height: 52,
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      paddingVertical: 0,
    },
    filtrosAplicados: {
      gap: ESPACIADO.minimo,
    },
    encabezadoFiltrosAplicados: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    textoFiltrosActivos: {
      flex: 1,
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    botonLimpiar: {
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: ESPACIADO.pequeno,
    },
    textoBotonLimpiar: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    enlaceLimpiar: {
      alignSelf: 'flex-start',
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      paddingVertical: ESPACIADO.minimo,
    },
    filaFiltrosAplicados: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      paddingRight: ESPACIADO.minimo,
    },
    chipFiltroAplicado: {
      alignItems: 'center',
      minHeight: 40,
      flexDirection: 'row',
      flexShrink: 0,
      gap: ESPACIADO.minimo,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.boton,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
    },
    textoChipFiltroAplicado: {
      color: tema.textoPrincipal,
      flexShrink: 1,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.medio,
    },
    listaOpciones: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    chip: {
      minHeight: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.circular,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    chipSeleccionado: {
      borderColor: tema.foco,
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : '#E8F1EE',
    },
    textoChip: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    textoChipSeleccionado: {
      color: tema.foco,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    chipFiltro: {
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    chipFiltroActivo: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    textoChipFiltro: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    textoChipFiltroActivo: {
      color: tema.textoPrincipal,
    },
    campoRango: {
      flex: 1,
      minWidth: 0,
      minHeight: 52,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingHorizontal: ESPACIADO.grande,
    },
    listaMovimientos: {
      gap: ESPACIADO.medio,
    },
    grupoDia: {
      gap: ESPACIADO.minimo,
    },
    tituloDia: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      paddingHorizontal: ESPACIADO.minimo,
    },
    movimientosDia: {
      gap: ESPACIADO.pequeno,
    },
    esqueletoMovimiento: {
      height: 64,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.fondoDeshabilitado,
    },
    filaMovimiento: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.medio,
    },
    filaPresionada: {
      opacity: 0.85,
    },
    iconoMovimiento: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    detalleMovimiento: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    filaCategoriaDescripcion: {
      flexDirection: 'row',
      alignItems: 'center',
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    categoriaMovimiento: {
      flexShrink: 1,
      maxWidth: '40%',
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    separadorMetadatos: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    descripcionEnLinea: {
      flex: 1,
      minWidth: 0,
      maxWidth: '100%',
    },
    nombreMovimiento: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    metaMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    tipoMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    montoMovimiento: {
      maxWidth: '38%',
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'right',
    },
    fondoFiltros: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingTop: ESPACIADO.pantalla,
    },
    overlayFiltros: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
    },
    fondoTactilFiltros: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    panelFiltros: {
      width: '100%',
      maxWidth: 480,
      maxHeight: '92%',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderTopLeftRadius: BORDES.radios.tarjeta,
      borderTopRightRadius: BORDES.radios.tarjeta,
      borderTopWidth: BORDES.anchos.fino,
      paddingTop: ESPACIADO.minimo,
      paddingBottom: ESPACIADO.medio,
      elevation: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
    },
    encabezadoPanelFiltros: {
      backgroundColor: tema.superficie,
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
      borderTopLeftRadius: BORDES.radios.tarjeta,
      borderTopRightRadius: BORDES.radios.tarjeta,
      paddingHorizontal: ESPACIADO.grande,
      paddingBottom: ESPACIADO.minimo,
    },
    manijaFiltros: {
      width: 36,
      height: 4,
      backgroundColor: tema.borde,
      borderRadius: BORDES.radios.circular,
    },
    zonaManijaFiltros: {
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    encabezadoPanelContenido: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    tituloPanelFiltros: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonCerrarFiltros: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollFiltros: {
      flexShrink: 1,
    },
    contenidoFiltrosScroll: {
      paddingHorizontal: ESPACIADO.grande,
      paddingTop: ESPACIADO.pequeno,
      paddingBottom: ESPACIADO.pantalla,
    },
    seccionFiltro: {
      backgroundColor: 'transparent',
    },
    encabezadoSeccionFiltro: {
      minHeight: 50,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.minimo,
    },
    detalleEncabezadoSeccionFiltro: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    acentoSeccionFiltro: {
      width: 3,
      height: 30,
      borderRadius: BORDES.radios.circular,
    },
    textosEncabezadoSeccionFiltro: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    tituloSeccionFiltro: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    resumenSeccionFiltro: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    contenidoSeccionFiltro: {
      gap: ESPACIADO.pequeno,
      paddingTop: ESPACIADO.pequeno,
      paddingBottom: ESPACIADO.medio,
      paddingHorizontal: ESPACIADO.minimo,
    },
    listaSeccionesFiltro: {
      gap: 0,
    },
    filaChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    chipFecha: {
      flex: 1,
      minWidth: 58,
      paddingHorizontal: ESPACIADO.medio,
    },
    grupoCalendarioFiltro: {
      gap: ESPACIADO.pequeno,
      paddingVertical: ESPACIADO.minimo,
    },
    textoAyudaFiltro: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    encabezadoCalendario: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    botonMes: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    mesCalendario: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    grillaMeses: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: ESPACIADO.pequeno,
    },
    opcionMes: {
      width: '31.5%',
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.minimo,
    },
    opcionMesActiva: {
      backgroundColor: tema.foco,
      borderColor: tema.foco,
    },
    textoOpcionMes: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.medio,
    },
    textoOpcionMesActivo: {
      color: tema.nombre === 'oscuro' ? tema.encabezado : tema.superficie,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    grupo: {
      gap: ESPACIADO.pequeno,
    },
    listaCategorias: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    tarjetaCategoriaFiltro: {
      width: anchoCategoriaFiltro,
      minHeight: 76,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.minimo,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
    },
    tarjetaCategoriaSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    nombreCategoria: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    piePanelFiltros: {
      alignItems: 'flex-end',
      paddingHorizontal: ESPACIADO.pantalla,
      paddingTop: ESPACIADO.pequeno,
      borderTopColor: tema.borde,
      borderTopWidth: BORDES.anchos.fino,
    },
    filaInformacion: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    etiquetaInformacion: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    valorInformacion: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      flexShrink: 1,
      textAlign: 'right',
    },
    filaDiasSemana: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    nombreDiaSemana: {
      width: '14.2857%',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    calendario: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    celdaCalendario: {
      width: '14.2857%',
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    diaCalendario: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'transparent',
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
    },
    diaCalendarioHoy: {
      borderColor: tema.foco,
    },
    diaCalendarioSeleccionado: {
      backgroundColor: tema.foco,
      borderColor: tema.foco,
    },
    textoDiaCalendario: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    textoDiaCalendarioSeleccionado: {
      color: tema.nombre === 'oscuro' ? tema.encabezado : tema.superficie,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    botonHoy: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'flex-end',
      paddingHorizontal: ESPACIADO.grande,
    },
    textoBotonHoy: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    estadoVacio: {
      minHeight: 190,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.grande,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
    },
    iconoEstadoVacio: {
      width: 52,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
      backgroundColor: tema.fondo,
    },
    textoEstadoVacio: {
      maxWidth: 280,
      textAlign: 'center',
    },
    fondoModal: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.48)',
      padding: ESPACIADO.pantalla,
    },
    fondoCierre: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    tarjetaOpciones: {
      width: '100%',
      maxWidth: 420,
      gap: ESPACIADO.medio,
      padding: ESPACIADO.extraGrande,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
      elevation: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.22,
      shadowRadius: 12,
    },
    encabezadoOpciones: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    iconoEncabezadoOpciones: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : '#E9F2EF',
    },
    detalleEncabezadoOpciones: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    tituloOpciones: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    opcionModal: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      paddingHorizontal: ESPACIADO.medio,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.superficie,
    },
    opcionEliminar: {
      borderColor: tema.error,
      backgroundColor: tema.errorFondo,
    },
    iconoOpcionModal: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : '#E9F2EF',
    },
    iconoOpcionEliminar: {
      backgroundColor: tema.superficie,
    },
    detalleOpcionModal: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    tituloOpcionModal: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    subtituloOpcionModal: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    textoOpcionEliminar: {
      color: tema.error,
    },
    botonCancelarModal: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    textoCancelarModal: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    tarjetaEdicion: {
      width: '100%',
      maxWidth: 480,
      maxHeight: '92%',
      overflow: 'hidden',
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
      elevation: 10,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
    },
    encabezadoModal: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
      paddingHorizontal: ESPACIADO.grande,
      paddingVertical: ESPACIADO.medio,
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
    },
    detalleEncabezadoEdicion: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    tituloEdicion: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    subtituloEdicion: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    contenidoModal: {
      flexShrink: 1,
    },
    botonCerrarModal: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    accionesEdicion: {
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
      paddingHorizontal: ESPACIADO.grande,
      paddingVertical: ESPACIADO.medio,
      borderTopColor: tema.borde,
      borderTopWidth: BORDES.anchos.fino,
    },
    botonPrincipalModal: {
      flex: 1,
      minHeight: 56,
    },
    accionesModal: {
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
      paddingTop: ESPACIADO.pequeno,
    },
    botonSecundarioModal: {
      flex: 1,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.boton,
      paddingHorizontal: ESPACIADO.pequeno,
    },
    textoSecundarioModal: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonPrincipal: {
      flex: 1,
      minHeight: 52,
    },
    botonPresionado: {
      opacity: 0.85,
    },
    textoBoton: {
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    textoProcesando: {
      color: tema.textoSecundario,
    },
    colorIndicador: tema.textoSecundario,
    tarjetaConfirmacion: {
      width: '100%',
      maxWidth: 420,
      gap: ESPACIADO.medio,
      padding: ESPACIADO.grande,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
      elevation: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.22,
      shadowRadius: 12,
    },
    encabezadoConfirmacion: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    iconoEliminar: {
      width: 52,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.errorFondo,
    },
    detalleConfirmacion: {
      gap: ESPACIADO.minimo,
    },
    tituloConfirmacion: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    textoConfirmacion: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      lineHeight: 20,
    },
    resumenDepositoEliminar: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      padding: ESPACIADO.medio,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.fondo,
    },
    iconoDepositoEliminar: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.campo,
    },
    datosDepositoEliminar: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    nombreDepositoEliminar: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    tipoDepositoEliminar: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    avisoEliminar: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.errorFondo,
    },
    textoAvisoEliminar: {
      flex: 1,
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      lineHeight: 18,
    },
    botonEliminar: {
      flex: 1,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.boton,
      backgroundColor: tema.error,
      paddingHorizontal: ESPACIADO.pequeno,
    },
    textoEliminar: {
      color: '#FFFFFF',
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
  });
}
