import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosDetalleDeposito(tema) {
  return StyleSheet.create({
    contenido: {
      width: '100%',
      maxWidth: 560,
      alignSelf: 'center',
      gap: ESPACIADO.grande,
      padding: ESPACIADO.pantalla,
      paddingBottom: ESPACIADO.enorme,
    },
    encabezadoDeposito: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    iconoDeposito: {
      width: 56,
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.tarjeta,
    },
    datosDeposito: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    botonOpciones: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
      backgroundColor: tema.fondo,
    },
    separadorSaldo: {
      height: BORDES.anchos.fino,
      marginVertical: ESPACIADO.grande,
      backgroundColor: tema.borde,
    },
    saldo: {
      marginTop: ESPACIADO.minimo,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo + 4,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    mensajeEstado: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : '#E9F2EF',
    },
    textoMensajeEstado: {
      flex: 1,
    },
    seccionMovimientos: {
      gap: ESPACIADO.medio,
    },
    busqueda: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      borderWidth: BORDES.anchos.normal,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.superficie,
      paddingLeft: ESPACIADO.medio,
      paddingRight: ESPACIADO.pequeno,
    },
    entradaBusqueda: {
      flex: 1,
      minWidth: 0,
      minHeight: 48,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.pequeno,
    },
    botonLimpiarBusqueda: {
      width: 40,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    botonFiltros: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
    },
    filaFiltrosTitulo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    textoBotonFiltros: {
      color: tema.textoPrincipal,
    },
    contadorFiltros: {
      minWidth: 22,
      height: 22,
      textAlign: 'center',
      overflow: 'hidden',
      color: tema.botonPrincipalTexto,
      backgroundColor: tema.botonPrincipal,
      borderRadius: BORDES.radios.circular,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      lineHeight: 22,
    },
    panelFiltros: {
      gap: ESPACIADO.medio,
      padding: ESPACIADO.medio,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
    },
    listaOpciones: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    chip: {
      minHeight: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.circular,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    chipSeleccionado: {
      borderColor: tema.foco,
      backgroundColor: tema.nombre === 'oscuro' ? tema.contenedorVerde : '#E8F1EE',
    },
    textoChip: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    textoChipSeleccionado: {
      color: tema.foco,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    filaCampos: {
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
    },
    campoRango: {
      flex: 1,
      minWidth: 0,
      minHeight: 46,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      paddingHorizontal: ESPACIADO.medio,
    },
    filtrosActivos: {
      gap: ESPACIADO.pequeno,
      paddingTop: ESPACIADO.pequeno,
      borderTopColor: tema.borde,
      borderTopWidth: BORDES.anchos.fino,
    },
    filtrosActivosCompactos: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.superficie,
    },
    textoFiltrosActivos: {
      flex: 1,
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    enlaceLimpiar: {
      alignSelf: 'flex-start',
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      paddingVertical: ESPACIADO.minimo,
    },
    listaMovimientos: {
      gap: ESPACIADO.pequeno,
    },
    esqueletoMovimiento: {
      height: 64,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.fondoDeshabilitado,
    },
    filaMovimiento: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
    },
    iconoMovimiento: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    detalleMovimiento: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    montoMovimiento: {
      maxWidth: '38%',
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'right',
    },
    elementoPresionado: {
      opacity: 0.72,
    },
    estadoVacio: {
      minHeight: 190,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.grande,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
    },
    iconoEstadoVacio: {
      width: 52,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
      backgroundColor: tema.fondo,
    },
    textoEstadoVacio: {
      maxWidth: 280,
      textAlign: 'center',
    },
    fondoModal: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.48)',
      padding: ESPACIADO.pantalla,
    },
    fondoCierre: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    tarjetaOpciones: {
      width: '100%',
      maxWidth: 420,
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.grande,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
    },
    opcionModal: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      paddingHorizontal: ESPACIADO.pequeno,
    },
    botonCancelarModal: {
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    textoCancelarModal: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    tarjetaEdicion: {
      width: '100%',
      maxWidth: 480,
      maxHeight: '92%',
      gap: ESPACIADO.medio,
      padding: ESPACIADO.grande,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
      elevation: 10,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
    },
    encabezadoModal: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    contenidoModal: {
      flexShrink: 1,
    },
    botonCerrarModal: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    grupoCampo: {
      gap: ESPACIADO.pequeno,
      marginBottom: ESPACIADO.medio,
    },
    listaIconos: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    opcionIcono: {
      flexGrow: 1,
      flexBasis: '28%',
      minWidth: 84,
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.campo,
      paddingHorizontal: ESPACIADO.pequeno,
    },
    opcionIconoSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    textoOpcionIcono: {
      flexShrink: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    listaColores: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    opcionColor: {
      flex: 1,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.circular,
    },
    opcionColorSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    campoDescripcion: {
      minHeight: 84,
      textAlignVertical: 'top',
      paddingTop: ESPACIADO.medio,
    },
    saldoNoEditable: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      paddingHorizontal: ESPACIADO.medio,
      borderRadius: BORDES.radios.campo,
      backgroundColor: tema.fondoDeshabilitado,
    },
    accionesModal: {
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
      paddingTop: ESPACIADO.pequeno,
    },
    botonSecundarioModal: {
      flex: 1,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      borderRadius: BORDES.radios.boton,
      paddingHorizontal: ESPACIADO.pequeno,
    },
    textoSecundarioModal: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonPrincipal: {
      flex: 1,
      minHeight: 52,
    },
    botonPresionado: {
      opacity: 0.82,
    },
    textoBoton: {
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    textoProcesando: {
      color: tema.textoSecundario,
    },
    colorIndicador: tema.textoSecundario,
    tarjetaConfirmacion: {
      width: '100%',
      maxWidth: 420,
      alignItems: 'center',
      gap: ESPACIADO.medio,
      padding: ESPACIADO.grande,
      borderRadius: BORDES.radios.tarjeta,
      backgroundColor: tema.superficie,
    },
    iconoEliminar: {
      width: 56,
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
      backgroundColor: tema.errorFondo,
    },
    tituloConfirmacion: {
      textAlign: 'center',
    },
    textoConfirmacion: {
      textAlign: 'center',
    },
    botonEliminar: {
      flex: 1,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.boton,
      backgroundColor: tema.error,
      paddingHorizontal: ESPACIADO.pequeno,
    },
    textoEliminar: {
      color: '#FFFFFF',
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
  });
}
