import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosEgreso(tema) {
  return StyleSheet.create({
    formulario: {
      gap: ESPACIADO.formulario,
      padding: ESPACIADO.pantalla,
      paddingBottom: ESPACIADO.enorme,
      maxWidth: 480,
      width: '100%',
      alignSelf: 'center',
    },
    grupo: {
      gap: ESPACIADO.pequeno,
    },
    filaMonto: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    simboloMonto: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo + 4,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    entradaMonto: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo + 4,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      paddingVertical: ESPACIADO.pequeno,
    },
    accionLimpiar: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filaDescripcion: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    entradaDescripcion: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.pequeno,
    },
    contador: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      textAlign: 'right',
    },
    tarjetaDeposito: {
      gap: ESPACIADO.minimo,
    },
    botonDeposito: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
      paddingVertical: ESPACIADO.medio,
    },
    botonDepositoEnfocado: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    botonDepositoError: {
      borderColor: tema.error,
      borderWidth: BORDES.anchos.normal,
    },
    iconoDeposito: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    textoDeposito: {
      flex: 1,
      minWidth: 0,
    },
    nombreDeposito: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    saldoDeposito: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    fondoSuperpuesto: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      padding: ESPACIADO.pantalla,
    },
    tarjetaSuperpuesta: {
      width: '100%',
      maxWidth: 480,
      maxHeight: '80%',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    encabezadoModal: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
      paddingLeft: ESPACIADO.pequeno,
    },
    tituloModal: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonCerrarModal: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollCategorias: {
      maxHeight: 480,
    },
    listaOpcionesCategoria: {
      gap: ESPACIADO.minimo,
      paddingVertical: ESPACIADO.minimo,
    },
    opcionCategoria: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionCategoriaSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    textoOpcionCategoria: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    opcionDeposito: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionDepositoSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    listaCategorias: {
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      width: '100%',
    },
    tarjetaCategoria: {
      flex: 1,
      minWidth: 0,
      minHeight: 72,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.minimo,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.minimo,
      paddingVertical: ESPACIADO.pequeno,
    },
    tarjetaMasCategorias: {
      borderColor: tema.foco,
      borderStyle: 'dashed',
    },
    tarjetaCategoriaSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    nombreCategoria: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar - 2,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    tarjetaInformacion: {
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    filaInformacion: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    separadorInformacion: {
      height: BORDES.anchos.fino,
      backgroundColor: tema.borde,
    },
    etiquetaInformacion: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    valorInformacion: {
      flexShrink: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'right',
    },
    tarjetaModalFecha: {
      width: '100%',
      maxWidth: 400,
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.medio,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    encabezadoCalendario: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    botonMes: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    mesCalendario: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    filaDiasSemana: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    nombreDiaSemana: {
      width: '14.2857%',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    calendario: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    celdaCalendario: {
      width: '14.2857%',
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    diaCalendario: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'transparent',
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
    },
    diaCalendarioHoy: {
      borderColor: tema.foco,
    },
    diaCalendarioSeleccionado: {
      backgroundColor: tema.foco,
      borderColor: tema.foco,
    },
    textoDiaCalendario: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    textoDiaCalendarioSeleccionado: {
      color: tema.nombre === 'oscuro' ? tema.encabezado : tema.superficie,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    botonHoy: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'flex-end',
      paddingHorizontal: ESPACIADO.grande,
    },
    textoBotonHoy: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    tarjetaModalHora: {
      width: '100%',
      maxWidth: 360,
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.grande,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    ayudaSelectorHora: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    selectoresHora: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.grande,
      paddingVertical: ESPACIADO.pequeno,
    },
    columnaHora: {
      alignItems: 'center',
      gap: ESPACIADO.minimo,
    },
    etiquetaSelectorHora: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    botonAjustarHora: {
      width: 48,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    valorSelectorHora: {
      minWidth: 72,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.monoespaciada,
      fontSize: 36,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      textAlign: 'center',
    },
    separadorHora: {
      marginTop: ESPACIADO.grande,
      color: tema.textoPrincipal,
      fontSize: TIPOGRAFIA.tamanos.titulo,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    accionesModal: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: ESPACIADO.pequeno,
      marginTop: ESPACIADO.pequeno,
    },
    botonModalSecundario: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderRadius: BORDES.radios.boton,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    textoBotonModalSecundario: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonModalPrincipal: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.botonPrincipal,
      borderRadius: BORDES.radios.boton,
      paddingHorizontal: ESPACIADO.grande,
    },
    textoBotonModalPrincipal: {
      color: tema.botonPrincipalTexto,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    grupoRecurrencia: {
      paddingBottom: ESPACIADO.medio,
    },
    contenedorFrecuencias: {
      gap: ESPACIADO.minimo,
      paddingTop: ESPACIADO.minimo,
    },
    etiquetaFrecuencias: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    filaFrecuencias: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.minimo,
    },
    botonFrecuencia: {
      flex: 1,
      minWidth: 62,
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.minimo,
    },
    botonFrecuenciaSeleccionado: {
      backgroundColor: tema.foco,
      borderColor: tema.foco,
    },
    textoFrecuencia: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    textoFrecuenciaSeleccionado: {
      color: tema.nombre === 'oscuro' ? tema.encabezado : tema.superficie,
    },
    errorCampo: {
      marginTop: -ESPACIADO.minimo,
    },
    mensajeError: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      backgroundColor: tema.errorFondo,
      borderColor: tema.error,
      borderRadius: 12,
      borderWidth: 1,
    },
    textoMensajeError: {
      flex: 1,
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      lineHeight: 20,
    },
    botonPrincipal: {
      minHeight: 56,
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
      marginTop: ESPACIADO.pequeno,
    },
    botonPresionado: {
      opacity: 0.82,
      transform: [{ scale: 0.99 }],
    },
    textoBoton: {
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    textoProcesando: {
      color: tema.textoSecundario,
    },
    colorIndicador: tema.textoSecundario,
    acciones: {
      gap: ESPACIADO.medio,
      marginTop: ESPACIADO.pequeno,
    },
  });
}
