import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosMovimientos(tema, anchoVentana = 390) {
  const columnasCategoriasFiltro = anchoVentana >= 420 ? 4 : 3;
  const anchoCategoriaFiltro = columnasCategoriasFiltro === 4 ? '22.5%' : '30%';
  const estiloTextoCategoriaDescripcion = {
    color: tema.textoPrincipal,
    fontFamily: TIPOGRAFIA.familias.principal,
    fontSize: TIPOGRAFIA.tamanos.secundario,
    fontWeight: TIPOGRAFIA.pesos.seminegrita,
  };

  return StyleSheet.create({
    contenido: {
      gap: ESPACIADO.formulario,
      padding: ESPACIADO.pantalla,
      paddingBottom: ESPACIADO.enorme,
      maxWidth: 480,
      width: '100%',
      alignSelf: 'center',
    },
    grupo: {
      gap: ESPACIADO.pequeno,
    },
    buscador: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      borderColor: tema.borde,
      borderWidth: BORDES.anchos.fino,
    },
    entradaBuscador: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.minimo,
    },
    accionBuscador: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filaBusqueda: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    filtrosAplicados: {
      gap: ESPACIADO.minimo,
    },
    encabezadoFiltrosAplicados: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    textoFiltrosActivos: {
      flex: 1,
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    botonFiltros: {
      height: 52,
      minHeight: 52,
      paddingVertical: 0,
      justifyContent: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    chipFecha: {
      flex: 1,
      minWidth: 58,
      paddingHorizontal: ESPACIADO.medio,
    },
    textoAyudaFiltro: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    grupoCalendarioFiltro: {
      gap: ESPACIADO.pequeno,
      paddingVertical: ESPACIADO.minimo,
    },
    seccionFiltro: {
      backgroundColor: 'transparent',
    },
    encabezadoSeccionFiltro: {
      minHeight: 50,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.minimo,
    },
    detalleEncabezadoSeccionFiltro: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
    },
    acentoSeccionFiltro: {
      width: 3,
      height: 30,
      borderRadius: BORDES.radios.circular,
    },
    textosEncabezadoSeccionFiltro: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    tituloSeccionFiltro: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    resumenSeccionFiltro: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    contenidoSeccionFiltro: {
      gap: ESPACIADO.pequeno,
      paddingTop: ESPACIADO.pequeno,
      paddingBottom: ESPACIADO.medio,
      paddingHorizontal: ESPACIADO.minimo,
    },
    tarjetaCategoriaFiltro: {
      width: anchoCategoriaFiltro,
      minHeight: 76,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.minimo,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
    },
    grillaMeses: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: ESPACIADO.pequeno,
    },
    opcionMes: {
      width: '31.5%',
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.minimo,
    },
    opcionMesActiva: {
      backgroundColor: tema.foco,
      borderColor: tema.foco,
    },
    textoOpcionMes: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.medio,
    },
    textoOpcionMesActivo: {
      color: tema.nombre === 'oscuro' ? tema.encabezado : tema.superficie,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    fondoFiltros: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingTop: ESPACIADO.pantalla,
    },
    overlayFiltros: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
    },
    fondoTactilFiltros: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    encabezadoPanelFiltros: {
      backgroundColor: tema.superficie,
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
      borderTopLeftRadius: BORDES.radios.tarjeta,
      borderTopRightRadius: BORDES.radios.tarjeta,
      paddingHorizontal: ESPACIADO.grande,
      paddingBottom: ESPACIADO.minimo,
    },
    zonaManijaFiltros: {
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    encabezadoPanelContenido: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    manijaFiltros: {
      width: 36,
      height: 4,
      backgroundColor: tema.borde,
      borderRadius: BORDES.radios.circular,
    },
    panelFiltros: {
      width: '100%',
      maxWidth: 480,
      maxHeight: '92%',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderTopLeftRadius: BORDES.radios.tarjeta,
      borderTopRightRadius: BORDES.radios.tarjeta,
      borderTopWidth: BORDES.anchos.fino,
      paddingTop: ESPACIADO.minimo,
      paddingBottom: ESPACIADO.medio,
      elevation: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
    },
    contenidoFiltrosScroll: {
      paddingHorizontal: ESPACIADO.grande,
      paddingTop: ESPACIADO.pequeno,
      paddingBottom: ESPACIADO.pantalla,
    },
    listaSeccionesFiltro: {
      gap: 0,
    },
    scrollFiltros: {
      flexShrink: 1,
    },
    filaFiltrosAplicados: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      paddingRight: ESPACIADO.minimo,
    },
    chipFiltroAplicado: {
      alignItems: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.boton,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      flexShrink: 0,
      gap: ESPACIADO.minimo,
      minHeight: 40,
      paddingHorizontal: ESPACIADO.medio,
    },
    textoChipFiltroAplicado: {
      color: tema.textoPrincipal,
      flexShrink: 1,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.medio,
    },
    filaChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    chip: {
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    chipActivo: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    textoChip: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    textoChipActivo: {
      color: tema.textoPrincipal,
    },
    botonLimpiar: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    textoBotonLimpiar: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    filaRango: {
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
    },
    campoRango: {
      flex: 1,
      minWidth: 0,
      minHeight: 52,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingHorizontal: ESPACIADO.grande,
    },
    listaMovimientos: {
      gap: ESPACIADO.medio,
    },
    grupoDia: {
      gap: ESPACIADO.minimo,
    },
    tituloDia: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      paddingHorizontal: ESPACIADO.minimo,
    },
    movimientosDia: {
      gap: ESPACIADO.pequeno,
    },
    filaMovimiento: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.medio,
    },
    filaPresionada: {
      opacity: 0.85,
    },
    iconoMovimiento: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    detalleMovimiento: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    filaCategoriaDescripcion: {
      flexDirection: 'row',
      alignItems: 'center',
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    categoriaMovimiento: {
      ...estiloTextoCategoriaDescripcion,
      flexShrink: 1,
      maxWidth: '40%',
    },
    separadorMetadatos: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    descripcionEnLinea: {
      flex: 1,
      minWidth: 0,
      maxWidth: '100%',
      ...estiloTextoCategoriaDescripcion,
    },
    nombreMovimiento: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    metaMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    tipoMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    montoMovimiento: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    estadoVacio: {
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.extraGrande,
    },
    textoEstadoVacio: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    lineaCarga: {
      height: 16,
      backgroundColor: tema.borde,
      borderRadius: BORDES.radios.campo,
    },
    tarjetaDeposito: {
      gap: ESPACIADO.minimo,
    },
    listaDepositos: {
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
    },
    listaDepositosFiltro: {
      gap: 0,
    },
    accionesDepositosFiltro: {
      flexDirection: 'row',
      gap: ESPACIADO.grande,
      paddingHorizontal: ESPACIADO.pequeno,
      paddingVertical: ESPACIADO.minimo,
    },
    textoAccionDepositoFiltro: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonDeposito: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
      paddingVertical: ESPACIADO.medio,
    },
    botonDepositoEnfocado: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    botonDepositoError: {
      borderColor: tema.error,
      borderWidth: BORDES.anchos.normal,
    },
    iconoDeposito: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    textoDeposito: {
      flex: 1,
      minWidth: 0,
    },
    nombreDeposito: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    saldoDeposito: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    fondoSuperpuesto: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      padding: ESPACIADO.pantalla,
    },
    tarjetaSuperpuesta: {
      width: '100%',
      maxWidth: 480,
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    opcionDeposito: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionDepositoSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    opcionDepositoFiltro: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderBottomColor: tema.borde,
      borderBottomWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.pequeno,
      paddingVertical: ESPACIADO.pequeno,
    },
    iconoDepositoFiltro: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.boton,
    },
    seleccionDepositoFiltro: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      marginLeft: ESPACIADO.pequeno,
    },
    listaCategorias: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    tarjetaCategoria: {
      width: 88,
      minHeight: 80,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
    },
    tarjetaCategoriaSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    tarjetaMasCategorias: {
      width: 104,
      minHeight: 88,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      borderStyle: 'dashed',
    },
    nombreCategoria: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    encabezadoModal: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: ESPACIADO.pequeno,
    },
    tituloModal: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonCerrarModal: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollCategorias: {
      maxHeight: 320,
    },
    listaOpcionesCategoria: {
      gap: ESPACIADO.pequeno,
      paddingBottom: ESPACIADO.pequeno,
    },
    opcionCategoria: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
    },
    opcionCategoriaSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    textoOpcionCategoria: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    errorCampo: {
      marginTop: -ESPACIADO.minimo,
    },
    filaInformacion: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    etiquetaInformacion: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    valorInformacion: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      flexShrink: 1,
      textAlign: 'right',
    },
    encabezadoCalendario: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    botonMes: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    mesCalendario: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    filaDiasSemana: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    nombreDiaSemana: {
      width: '14.2857%',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    calendario: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    celdaCalendario: {
      width: '14.2857%',
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    diaCalendario: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'transparent',
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
    },
    diaCalendarioHoy: {
      borderColor: tema.foco,
    },
    diaCalendarioSeleccionado: {
      backgroundColor: tema.foco,
      borderColor: tema.foco,
    },
    textoDiaCalendario: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    textoDiaCalendarioSeleccionado: {
      color: tema.nombre === 'oscuro' ? tema.encabezado : tema.superficie,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    botonHoy: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'flex-end',
      paddingHorizontal: ESPACIADO.grande,
    },
    textoBotonHoy: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
  });
}
