import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosMovimientos(tema) {
  return StyleSheet.create({
    contenido: {
      gap: ESPACIADO.formulario,
      padding: ESPACIADO.pantalla,
      paddingBottom: ESPACIADO.enorme,
      maxWidth: 480,
      width: '100%',
      alignSelf: 'center',
    },
    grupo: {
      gap: ESPACIADO.pequeno,
    },
    buscador: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.contenedorVerde,
      borderRadius: BORDES.radios.contenedor,
      paddingHorizontal: ESPACIADO.grande,
    },
    entradaBuscador: {
      flex: 1,
      minWidth: 0,
      color: tema.contenedorVerdeTexto,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.pequeno,
    },
    accionBuscador: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filaFiltros: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ESPACIADO.pequeno,
    },
    textoFiltrosActivos: {
      flex: 1,
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    botonFiltros: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.contenedorVerde,
      borderRadius: BORDES.radios.boton,
      paddingHorizontal: ESPACIADO.grande,
    },
    textoBotonFiltros: {
      color: tema.botonPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    filaChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    chip: {
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    chipActivo: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    textoChip: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    textoChipActivo: {
      color: tema.textoPrincipal,
    },
    botonLimpiar: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    textoBotonLimpiar: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    filaRango: {
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
    },
    campoRango: {
      flex: 1,
      minWidth: 0,
      minHeight: 52,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingHorizontal: ESPACIADO.grande,
    },
    listaMovimientos: {
      gap: ESPACIADO.pequeno,
    },
    filaMovimiento: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.medio,
    },
    filaPresionada: {
      opacity: 0.85,
    },
    iconoMovimiento: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    detalleMovimiento: {
      flex: 1,
      minWidth: 0,
      gap: ESPACIADO.minimo,
    },
    nombreMovimiento: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    metaMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    tipoMovimiento: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    montoMovimiento: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    estadoVacio: {
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.extraGrande,
    },
    textoEstadoVacio: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    lineaCarga: {
      height: 16,
      backgroundColor: tema.borde,
      borderRadius: BORDES.radios.campo,
    },
    tarjetaDeposito: {
      gap: ESPACIADO.minimo,
    },
    listaDepositos: {
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
    },
    botonDeposito: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
      paddingVertical: ESPACIADO.medio,
    },
    botonDepositoEnfocado: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    botonDepositoError: {
      borderColor: tema.error,
      borderWidth: BORDES.anchos.normal,
    },
    iconoDeposito: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    textoDeposito: {
      flex: 1,
      minWidth: 0,
    },
    nombreDeposito: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    saldoDeposito: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    fondoSuperpuesto: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      padding: ESPACIADO.pantalla,
    },
    tarjetaSuperpuesta: {
      width: '100%',
      maxWidth: 480,
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    opcionDeposito: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionDepositoSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    listaCategorias: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ESPACIADO.pequeno,
    },
    tarjetaCategoria: {
      width: 88,
      minHeight: 80,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.pequeno,
    },
    tarjetaCategoriaSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    tarjetaMasCategorias: {
      width: 104,
      minHeight: 88,
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      borderStyle: 'dashed',
    },
    nombreCategoria: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    encabezadoModal: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: ESPACIADO.pequeno,
    },
    tituloModal: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonCerrarModal: {
      minWidth: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollCategorias: {
      maxHeight: 320,
    },
    listaOpcionesCategoria: {
      gap: ESPACIADO.pequeno,
      paddingBottom: ESPACIADO.pequeno,
    },
    opcionCategoria: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
    },
    opcionCategoriaSeleccionada: {
      borderColor: tema.foco,
      borderWidth: BORDES.anchos.normal,
    },
    textoOpcionCategoria: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    errorCampo: {
      marginTop: -ESPACIADO.minimo,
    },
    filaInformacion: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    etiquetaInformacion: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    valorInformacion: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    encabezadoCalendario: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    botonMes: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BORDES.radios.circular,
    },
    mesCalendario: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    filaDiasSemana: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    nombreDiaSemana: {
      width: '14.2857%',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    calendario: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    celdaCalendario: {
      width: '14.2857%',
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    diaCalendario: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'transparent',
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
    },
    diaCalendarioHoy: {
      borderColor: tema.foco,
    },
    diaCalendarioSeleccionado: {
      backgroundColor: tema.foco,
      borderColor: tema.foco,
    },
    textoDiaCalendario: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    textoDiaCalendarioSeleccionado: {
      color: tema.nombre === 'oscuro' ? tema.encabezado : tema.superficie,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    botonHoy: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'flex-end',
      paddingHorizontal: ESPACIADO.grande,
    },
    textoBotonHoy: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
  });
}
