import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosPerfil(tema) {
  return StyleSheet.create({
    contenido: {
      gap: ESPACIADO.medio,
      padding: ESPACIADO.grande,
      paddingBottom: ESPACIADO.enorme,
      maxWidth: 480,
      width: '100%',
      alignSelf: 'center',
    },
    grupo: {
      gap: ESPACIADO.pequeno,
    },
    tituloGrupo: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    tarjetaUsuario: {
      alignItems: 'stretch',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.grande,
    },
    resumenUsuario: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.medio,
    },
    columnaAvatar: {
      width: 92,
      alignItems: 'center',
      gap: ESPACIADO.minimo,
    },
    detalleUsuario: {
      flex: 1,
      minWidth: 0,
      alignSelf: 'stretch',
      justifyContent: 'space-between',
    },
    datosUsuario: {
      gap: ESPACIADO.minimo,
    },
    avatar: {
      width: 76,
      height: 76,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.contenedorVerde,
      borderRadius: BORDES.radios.circular,
    },
    imagenAvatar: {
      width: '100%',
      height: '100%',
      borderRadius: BORDES.radios.circular,
    },
    inicialesAvatar: {
      color: tema.botonPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    nombreUsuario: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      textAlign: 'left',
      lineHeight: 40,
      flexShrink: 1,
    },
    correoUsuario: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'left',
    },
    fechaRegistro: {
      minHeight: 26,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: ESPACIADO.minimo,
    },
    textoFechaRegistro: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: 12,
      lineHeight: 13,
      textAlign: 'left',
      flexShrink: 1,
      includeFontPadding: false,
    },
    accionFoto: {
      minHeight: 28,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: ESPACIADO.minimo,
    },
    accionesFoto: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
    },
    accionFotoCompacta: {
      flex: 1,
      minWidth: 0,
      paddingHorizontal: 0,
    },
    textoAccionFoto: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
      textAlign: 'center',
    },
    textoQuitarFoto: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      textAlign: 'center',
    },
    tarjetaOpciones: {
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    filaOpcion: {
      minHeight: 60,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    filaOpcionDeshabilitada: {
      opacity: 0.62,
    },
    filaCerrarSesion: {
      minHeight: 60,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.medio,
    },
    filaSelector: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    iconoSelector: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.fondo,
      borderRadius: BORDES.radios.campo,
    },
    iconoPeligro: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#9E4A4A',
      borderRadius: BORDES.radios.campo,
    },
    contenidoSelector: {
      flex: 1,
      minWidth: 0,
      alignSelf: 'stretch',
      justifyContent: 'center',
      gap: ESPACIADO.minimo,
    },
    contenidoOpcionAvanzada: {
      flex: 1,
      minWidth: 0,
      alignSelf: 'stretch',
      justifyContent: 'center',
      gap: ESPACIADO.minimo,
    },
    textoFilaSelector: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    descripcionAvanzada: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    valorSelector: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
    },
    separadorOpcion: {
      height: BORDES.anchos.fino,
      backgroundColor: tema.borde,
    },
    textoOpcion: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    valorOpcion: {
      width: '100%',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'right',
    },
    textoOpcionPeligro: {
      flex: 1,
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    fondoSuperpuesto: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      padding: ESPACIADO.pantalla,
    },
    tarjetaSuperpuesta: {
      width: '100%',
      maxWidth: 480,
      maxHeight: '90%',
      alignSelf: 'center',
      alignItems: 'stretch',
      gap: ESPACIADO.medio,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.grande,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    encabezadoFormularioModal: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ESPACIADO.pequeno,
    },
    iconoEncabezadoFormularioModal: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.fondo,
      borderRadius: BORDES.radios.circular,
    },
    cuerpoEncabezadoFormularioModal: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-start',
      gap: ESPACIADO.minimo,
      paddingTop: ESPACIADO.minimo,
    },
    tituloFormularioModal: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      textAlign: 'left',
    },
    descripcionFormularioModal: {
      alignSelf: 'stretch',
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      lineHeight: 20,
      textAlign: 'left',
    },
    botonCerrarFormularioModal: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.fondo,
      borderRadius: BORDES.radios.circular,
    },
    botonCerrarFormularioModalPresionado: {
      opacity: 0.65,
    },
    desplazamientoModal: {
      width: '100%',
      flexShrink: 1,
    },
    contenidoScrollModal: {
      width: '100%',
      alignItems: 'stretch',
    },
    formularioModal: {
      width: '100%',
      alignItems: 'stretch',
      gap: ESPACIADO.medio,
    },
    grupoCampoModal: {
      width: '100%',
      alignItems: 'stretch',
      gap: ESPACIADO.minimo,
    },
    separadorModal: {
      width: '100%',
      height: BORDES.anchos.fino,
      backgroundColor: tema.borde,
    },
    listaOpcionesModal: {
      width: '100%',
      alignItems: 'stretch',
      gap: ESPACIADO.pequeno,
    },
    contenedorOpcionModal: {
      width: '100%',
      alignSelf: 'stretch',
    },
    textoAyudaModal: {
      width: '100%',
      lineHeight: 18,
      textAlign: 'center',
    },
    botonBiometria: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.fondo,
      borderColor: tema.foco,
      borderRadius: BORDES.radios.boton,
      borderWidth: BORDES.anchos.normal,
      paddingHorizontal: ESPACIADO.grande,
    },
    botonBiometriaDeshabilitado: {
      opacity: 0.65,
    },
    textoBotonBiometria: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    campoEdicion: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    botonVisibilidad: {
      minWidth: 36,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    entradaEdicion: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionSelector: {
      width: '100%',
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
      backgroundColor: tema.fondo,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionSelectorActiva: {
      borderColor: tema.foco,
      backgroundColor: tema.superficie,
    },
    iconoSelectorModal: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.superficie,
      borderRadius: BORDES.radios.circular,
    },
    iconoSelectorModalActivo: {
      backgroundColor: tema.contenedorVerde,
    },
    contenidoOpcionSelector: {
      flex: 1,
      minWidth: 0,
      alignSelf: 'stretch',
      justifyContent: 'center',
      gap: ESPACIADO.minimo,
    },
    textoOpcionSelector: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    descripcionOpcionSelector: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      lineHeight: 16,
    },
    botonPeligro: {
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.error,
      borderRadius: BORDES.radios.boton,
      paddingHorizontal: ESPACIADO.grande,
      paddingVertical: ESPACIADO.medio,
    },
    textoBotonPeligro: {
      color: '#FFFFFF',
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    mensajeError: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      backgroundColor: tema.errorFondo,
      borderColor: tema.error,
      borderRadius: 12,
      borderWidth: 1,
    },
    textoMensajeError: {
      flex: 1,
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      lineHeight: 20,
    },
    botonPrincipal: {
      minHeight: 56,
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
    },
    botonPresionado: {
      opacity: 0.82,
      transform: [{ scale: 0.99 }],
    },
    textoBoton: {
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    textoProcesando: {
      color: tema.textoSecundario,
    },
    colorIndicador: tema.textoSecundario,
    lineaCarga: {
      height: 16,
      backgroundColor: tema.borde,
      borderRadius: BORDES.radios.campo,
    },
  });
}
