import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosPerfil(tema) {
  return StyleSheet.create({
    contenido: {
      gap: ESPACIADO.formulario,
      padding: ESPACIADO.pantalla,
      paddingBottom: ESPACIADO.enorme,
      maxWidth: 480,
      width: '100%',
      alignSelf: 'center',
    },
    grupo: {
      gap: ESPACIADO.pequeno,
    },
    tituloGrupo: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    tarjetaUsuario: {
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.extraGrande,
    },
    avatar: {
      width: 88,
      height: 88,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.contenedorVerde,
      borderRadius: BORDES.radios.circular,
    },
    inicialesAvatar: {
      color: tema.botonPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.titulo,
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    nombreUsuario: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      textAlign: 'center',
    },
    correoUsuario: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    accionFoto: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: ESPACIADO.grande,
    },
    textoAccionFoto: {
      color: tema.foco,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    tarjetaOpciones: {
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    filaOpcion: {
      minHeight: 60,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    separadorOpcion: {
      height: BORDES.anchos.fino,
      backgroundColor: tema.borde,
    },
    textoOpcion: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    valorOpcion: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    textoOpcionPeligro: {
      flex: 1,
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    fondoSuperpuesto: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      padding: ESPACIADO.pantalla,
    },
    tarjetaSuperpuesta: {
      width: '100%',
      maxWidth: 480,
      gap: ESPACIADO.formulario,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      padding: ESPACIADO.extraGrande,
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    tituloModal: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.negrita,
      textAlign: 'center',
    },
    descripcionModal: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    campoEdicion: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.pequeno,
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      paddingHorizontal: ESPACIADO.grande,
    },
    entradaEdicion: {
      flex: 1,
      minWidth: 0,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
      paddingVertical: ESPACIADO.pequeno,
    },
    opcionIdioma: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ESPACIADO.medio,
    },
    textoIdioma: {
      flex: 1,
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    botonPeligro: {
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tema.error,
      borderRadius: BORDES.radios.boton,
      paddingHorizontal: ESPACIADO.grande,
      paddingVertical: ESPACIADO.medio,
    },
    textoBotonPeligro: {
      color: '#FFFFFF',
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.boton,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    mensajeError: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ESPACIADO.pequeno,
      padding: ESPACIADO.medio,
      backgroundColor: tema.errorFondo,
      borderColor: tema.error,
      borderRadius: 12,
      borderWidth: 1,
    },
    textoMensajeError: {
      flex: 1,
      color: tema.error,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      lineHeight: 20,
    },
    botonPrincipal: {
      minHeight: 56,
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
    },
    botonPresionado: {
      opacity: 0.82,
      transform: [{ scale: 0.99 }],
    },
    textoBoton: {
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    textoProcesando: {
      color: tema.textoSecundario,
    },
    colorIndicador: tema.textoSecundario,
    lineaCarga: {
      height: 16,
      backgroundColor: tema.borde,
      borderRadius: BORDES.radios.campo,
    },
  });
}
