import { StyleSheet } from 'react-native';

import { BORDES, ESPACIADO, TIPOGRAFIA } from './globalStyles';

export function crearEstilosEstadisticas(tema) {
  return StyleSheet.create({
    contenidoDesplazable: {
      flexGrow: 1,
      paddingBottom: ESPACIADO.grande,
      paddingHorizontal: ESPACIADO.pantalla,
    },
    desplazamiento: {
      flex: 1,
    },
    controles: {
      gap: ESPACIADO.pequeno,
      paddingTop: ESPACIADO.medio,
    },
    filaTipoMovimiento: {
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.boton,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      padding: ESPACIADO.minimo,
    },
    botonTipoMovimiento: {
      alignItems: 'center',
      borderRadius: BORDES.radios.boton,
      flex: 1,
      justifyContent: 'center',
      minHeight: 40,
    },
    botonTipoMovimientoActivo: {
      backgroundColor: tema.encabezado,
    },
    textoBotonTipo: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    textoBotonTipoActivo: {
      color: tema.encabezadoTexto,
    },
    desplazamientoSelectores: {
      alignSelf: 'stretch',
      flexGrow: 0,
      width: '100%',
    },
    filaSelectores: {
      alignItems: 'center',
      flexDirection: 'row',
      flexGrow: 1,
      gap: ESPACIADO.minimo,
      minWidth: '100%',
    },
    botonSelector: {
      alignItems: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.boton,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      flexGrow: 1,
      gap: ESPACIADO.minimo,
      justifyContent: 'space-between',
      flexShrink: 0,
      minHeight: 40,
      paddingHorizontal: ESPACIADO.medio,
    },
    textoSelector: {
      color: tema.textoPrincipal,
      flexShrink: 1,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      fontWeight: TIPOGRAFIA.pesos.medio,
    },
    botonSelectorCategoria: {
      alignItems: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.boton,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      flexGrow: 1,
      flexShrink: 0,
      gap: ESPACIADO.minimo,
      justifyContent: 'center',
      minHeight: 40,
      paddingHorizontal: ESPACIADO.medio,
    },
    cabeceraGrafico: {
      gap: ESPACIADO.minimo,
      paddingTop: ESPACIADO.grande,
    },
    contenedorCarrusel: {
      width: '100%',
    },
    carrusel: {
      width: '100%',
    },
    contenidoCarrusel: {
      alignItems: 'flex-start',
      flexDirection: 'row',
    },
    paginaGrafico: {
      flexShrink: 0,
    },
    indicadoresCarrusel: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      justifyContent: 'center',
      paddingBottom: ESPACIADO.minimo,
      paddingTop: ESPACIADO.medio,
    },
    indicadorCarrusel: {
      backgroundColor: tema.borde,
      borderRadius: BORDES.radios.circular,
      height: 8,
      width: 8,
    },
    indicadorCarruselActivo: {
      backgroundColor: tema.foco,
      width: 20,
    },
    tituloGrafico: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    subtituloGrafico: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    contenedorGraficoCircular: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 288,
      paddingVertical: ESPACIADO.pequeno,
    },
    textoSinCategorias: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    detalleSeleccion: {
      alignItems: 'center',
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      justifyContent: 'center',
      marginTop: ESPACIADO.medio,
      minHeight: 62,
      paddingHorizontal: ESPACIADO.medio,
      paddingVertical: ESPACIADO.pequeno,
    },
    tituloDetalleSeleccion: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    filaDetalleSeleccion: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      justifyContent: 'center',
    },
    textoDetalleSeleccion: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    listaCategorias: {
      gap: ESPACIADO.minimo,
      paddingTop: ESPACIADO.medio,
    },
    filaCategoria: {
      alignItems: 'center',
      backgroundColor: tema.superficie,
      borderColor: 'transparent',
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
      minHeight: 52,
      paddingHorizontal: ESPACIADO.medio,
    },
    filaCategoriaActiva: {
      borderColor: tema.foco,
    },
    muestraColor: {
      borderRadius: BORDES.radios.circular,
      height: 12,
      width: 12,
    },
    nombreCategoria: {
      color: tema.textoPrincipal,
      flex: 1,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
    },
    porcentajeCategoria: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      minWidth: 34,
      textAlign: 'right',
    },
    montoCategoria: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      minWidth: 78,
      textAlign: 'right',
    },
    contenedorColumnas: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      gap: ESPACIADO.minimo,
      justifyContent: 'space-between',
      paddingBottom: ESPACIADO.minimo,
      paddingHorizontal: ESPACIADO.minimo,
      paddingTop: ESPACIADO.grande,
      width: '100%',
    },
    columna: {
      alignItems: 'center',
      flex: 1,
      height: '100%',
      justifyContent: 'flex-end',
      minWidth: 0,
    },
    barra: {
      borderRadius: BORDES.radios.boton,
      borderWidth: 2,
      flexDirection: 'column-reverse',
      overflow: 'hidden',
      width: '100%',
    },
    segmentoBarra: {
      width: '100%',
    },
    etiquetaColumna: {
      color: tema.textoSecundario,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: 10,
      height: 20,
      paddingTop: ESPACIADO.minimo,
      textAlign: 'center',
      width: '100%',
    },
    detalleColumna: {
      backgroundColor: tema.superficie,
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      marginTop: ESPACIADO.medio,
      padding: ESPACIADO.medio,
    },
    resumenColumna: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 32,
    },
    totalColumna: {
      color: tema.textoPrincipal,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    listaDetalleColumna: {
      gap: ESPACIADO.minimo,
      paddingTop: ESPACIADO.pequeno,
    },
    filaDetalleColumna: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: ESPACIADO.pequeno,
      minHeight: 28,
    },
    fondoModal: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
      padding: ESPACIADO.pantalla,
    },
    fondoTocable: {
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    tarjetaModal: {
      borderColor: tema.borde,
      borderRadius: BORDES.radios.tarjeta,
      borderWidth: BORDES.anchos.fino,
      elevation: 8,
      maxHeight: '82%',
      maxWidth: 480,
      padding: ESPACIADO.medio,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      width: '100%',
      zIndex: 1,
    },
    encabezadoModal: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 48,
      paddingLeft: ESPACIADO.pequeno,
    },
    tituloModal: {
      color: tema.textoPrincipal,
      flex: 1,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.encabezado,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    botonCerrarModal: {
      alignItems: 'center',
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    accionesCategorias: {
      flexDirection: 'row',
      gap: ESPACIADO.grande,
      paddingHorizontal: ESPACIADO.pequeno,
      paddingVertical: ESPACIADO.minimo,
    },
    textoAccionCategorias: {
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    opcionesModal: {
      gap: ESPACIADO.minimo,
      paddingTop: ESPACIADO.pequeno,
    },
    opcionModal: {
      alignItems: 'center',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 48,
      paddingHorizontal: ESPACIADO.medio,
    },
    opcionCategoria: {
      alignItems: 'center',
      borderRadius: BORDES.radios.campo,
      borderWidth: BORDES.anchos.fino,
      flexDirection: 'row',
      gap: ESPACIADO.medio,
      minHeight: 48,
      paddingHorizontal: ESPACIADO.medio,
    },
    textoOpcionModal: {
      color: tema.textoPrincipal,
      flex: 1,
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.cuerpo,
    },
    encabezadoCalendario: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: ESPACIADO.pequeno,
    },
    botonMesCalendario: {
      alignItems: 'center',
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    mesCalendario: {
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
    cuadriculaCalendario: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    nombreDiaCalendario: {
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.auxiliar,
      height: 32,
      lineHeight: 32,
      textAlign: 'center',
      width: '14.2857%',
    },
    celdaCalendario: {
      alignItems: 'center',
      aspectRatio: 1,
      justifyContent: 'center',
      width: '14.2857%',
    },
    diaCalendario: {
      alignItems: 'center',
      borderColor: 'transparent',
      borderRadius: BORDES.radios.circular,
      borderWidth: BORDES.anchos.fino,
      height: 38,
      justifyContent: 'center',
      width: 38,
    },
    diaCalendarioHoy: {
      borderColor: tema.foco,
    },
    diaCalendarioSeleccionado: {
      backgroundColor: tema.foco,
    },
    textoDiaCalendario: {
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      textAlign: 'center',
    },
    textoDiaCalendarioSeleccionado: {
      fontWeight: TIPOGRAFIA.pesos.negrita,
    },
    botonHoyCalendario: {
      alignItems: 'center',
      minHeight: 44,
      justifyContent: 'center',
      marginTop: ESPACIADO.pequeno,
    },
    textoBotonHoyCalendario: {
      fontFamily: TIPOGRAFIA.familias.principal,
      fontSize: TIPOGRAFIA.tamanos.secundario,
      fontWeight: TIPOGRAFIA.pesos.seminegrita,
    },
  });
}
